server:
  port: 8082

spring:
  application:
    name: my-second-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true